config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  resources :artists, only: [:new, :create, :show] do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:index]

  resources :users, only: [:new, :create, :show]

  namespace :admin do
    resources :categories, only: [:index]
  end

  resources :carts, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name
  has_many :songs
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || Hash.new(0)
  end

  def total_count
    @contents.values.sum
  end

  def add_song(song_id)
    @contents[song_id.to_s] += 1
  end

  def count_of(song_id)
    @contents[song_id.to_s].to_i
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :password, require: true
  validates :username, presence: true, uniqueness: true

  has_secure_password

  enum role: %w(default admin)
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :require_admin

  def index
  end


  private

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :build_cart

  # this lets the view access the helper method
  helper_method :current_user

  def current_user
    @current_user_lookup ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def build_cart
    @cart ||= Cart.new(session[:cart])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def new
    @artist = Artist.new
  end

  def create
    new_artist = Artist.create(artist_params)
    redirect_to artist_path(new_artist)
  end

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
  end

  private
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    song = Song.find(params[:song_id])

    @cart.add_song(song.id)
    session[:cart] = @cart.contents
    quantity = @cart.count_of(song.id)

    flash[:notice] = "You have #{pluralize(quantity, "copy")} of #{song.title} in your cart"
    redirect_to songs_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = Song.new
  end

  def create
    artist = Artist.find(params[:artist_id])
    artist.songs.create(song_params)
    redirect_to artist_path(artist)
  end

  private
    def song_params
      params.require(:song).permit(:title, :length, :play_count)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>Admin Categories</h1>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "artist" %>
  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>

<% if !@songs.empty? %>
  <% @songs.each do |song| %>
    <%= song.title %>
    <%= song.length %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BadTracks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      Cart: <%= @cart.total_count %>
    </nav>

    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: type %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<% @songs.each do |song| %>
 <%=song.title %>
 <li>Plays: <%= song.play_count %></li>
 <%= button_to 'Add Song', carts_path(song_id: song.id) %>
<% end %>

app/views/songs/new.html.erb
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title %>
  <%= f.label :length %>
  <%= f.number_field :length %>
  <%= f.label :play_count %>
  <%= f.number_field :play_count %>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username %></h1>

app/views/welcome/index.html.erb
<%= link_to 'Sign up to be a new user', new_user_path %>
<%= link_to "I already have an account", login_path %>